package queries

const CreateEventsTable = `
    CREATE TABLE IF NOT EXISTS events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id VARCHAR(64) NOT NULL,            -- Associa o evento à sessão do page_view
        event_type VARCHAR(50) NOT NULL,             -- ex: 'click_cta', 'scroll_depth', 'video_play'
        event_label VARCHAR(100) NOT NULL,            -- ex: 'btn_hero_comprar', 'scroll_75', 'whatsapp_click'
        metadata JSONB,                              -- Dados extras flexíveis (ex: {"form_id": "contact"})
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_events_session ON events (session_id);
    CREATE INDEX IF NOT EXISTS idx_events_type_label ON events (event_type, event_label);
    CREATE INDEX IF NOT EXISTS idx_events_created_at ON events (created_at);
`

const CreateEvent = `
    INSERT INTO events (
        session_id,
        event_type,
        event_label,
        metadata
    ) VALUES (
        :session_id,
        :event_type,
        :event_label,
        :metadata
    )
`

const ListEvents = `
SELECT * FROM events 
WHERE ($1::bigint = 0 OR id < $1) 
ORDER BY created_at DESC 
LIMIT $2
`
