package queries

const CreateLeadsTable = `
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64),                      -- Associa o lead à sessão de tráfego
    name VARCHAR(120) NOT NULL,
    email VARCHAR(200) NOT NULL,
    company VARCHAR(200) NOT NULL,
    phone VARCHAR(20),
    description TEXT,
    
    -- UTMs no momento da conversão (para attribution fácil)
    utm_source VARCHAR(100),
    utm_campaign VARCHAR(100),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads (created_at);
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads (email);
`

const CreateLead = `
INSERT INTO leads (
    session_id,
    name,
    email,
    company,
    phone,
    description,
    utm_source,
    utm_campaign
) VALUES (
    :session_id,
    :name,
    :email,
    :company,
    :description,
    :phone,
    :utm_source,
    :utm_campaign
)`

const ListLeads = `
SELECT * FROM leads 
WHERE ($1::bigint = 0 OR id < $1) 
ORDER BY created_at DESC 
LIMIT $2
`
