package queries

const CreatePageViewsTable = `
CREATE TABLE IF NOT EXISTS page_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,            -- Hash ou UUID da sessão (gerado no cliente ou server)
    visitor_hash VARCHAR(64) NOT NULL,          -- Hash (ex: SHA256 do IP + UserAgent) para contar visitantes únicos com LGPD
    page_path VARCHAR(255) NOT NULL DEFAULT '/', -- Caminho acessado (ex: / ou /obrigado)
    
    -- Métricas de Origem / UTMs
    referrer VARCHAR(500),                       -- URL de onde o usuário veio
    utm_source VARCHAR(100),                     -- ex: google, instagram, facebook
    utm_medium VARCHAR(100),                     -- ex: cpc, bio, story
    utm_campaign VARCHAR(100),                   -- ex: lancamento_setembro
    utm_term VARCHAR(100),                       -- palavra-chave do anúncio
    utm_content VARCHAR(100),                    -- variação do anúncio
    
    -- Dispositivo e Navegador
    device_type VARCHAR(20),                     -- desktop, mobile, tablet
    browser VARCHAR(50),                         -- Chrome, Safari, Firefox
    os VARCHAR(50),                              -- Windows, iOS, Android, macOS
    
    duration_seconds INT DEFAULT 0,              -- Tempo total de permanência (atualizado via beacon/unload)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Índices cruciais para relatórios rápidos no painel admin
CREATE INDEX IF NOT EXISTS idx_page_views_created_at ON page_views (created_at);
CREATE INDEX IF NOT EXISTS idx_page_views_session ON page_views (session_id);
CREATE INDEX IF NOT EXISTS idx_page_views_utm ON page_views (utm_source, utm_campaign);
`

const CreatePageView = `
INSERT INTO page_views (
    session_id,
    visitor_hash,
    page_path,
    referrer,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_term,
    utm_content,
    device_type,
    browser,
    os,
    duration_seconds
) VALUES (
    :session_id,
    :visitor_hash,
    :page_path,
    :referrer,
    :utm_source,
    :utm_medium,
    :utm_campaign,
    :utm_term,
    :utm_content,
    :device_type,
    :browser,
    :os,
    :duration_seconds
)`

const ListPageViews = `
SELECT * FROM page_views 
WHERE ($1::bigint = 0 OR id < $1) 
ORDER BY created_at DESC 
LIMIT $2
`
