package queries

const CreateUserTable = `
CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	
    name VARCHAR(120) NOT NULL,
    email VARCHAR(200) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
`

const CreateUser = `
INSERT INTO users (name, email, password_hash) VALUES (:name, :email, ":password_hash")
`
